# Generated by Django 4.0.6 on 2022-07-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_note_delete_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='date_updated',
            field=models.DateTimeField(null=True),
        ),
    ]
