# Generated by Django 4.0.6 on 2022-07-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_alter_customer_date_updated_alter_event_date_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='type',
        ),
        migrations.AddField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('SIGNE', 'Signé'), ('EN COURS', 'En cours')], default='En cours', max_length=15),
        ),
    ]
