# Generated by Django 4.0.6 on 2022-07-23 12:25

from django.db import migrations
import management.models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_users_mobile_alter_users_phone'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='users',
            managers=[
                ('objects', management.models.CustomUserManager()),
            ],
        ),
    ]
