# Generated by Django 4.0.6 on 2022-07-23 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_users_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='users',
            managers=[
            ],
        ),
    ]
